import { Lato } from "next/font/google";
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import "./globals.css";
import '@flaticon/flaticon-uicons/css/all/all.css'

const lato = Lato({ weight: '300', preload: false});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lato.className}  bg-gray-200`}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
